<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles\BorderRadius\Definitions;

class RadiusType extends \Lenra\App\Base\Components\Styles\BorderRadius\Definitions\RadiusTypeBase {
  // Add here custom implementations

  public static function builder(): RadiusType {
    return new RadiusType();
  }
}
