<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\View\Definitions;

class Find extends \Lenra\App\Base\Components\View\Definitions\FindBase {
  // Add here custom implementations

  public static function builder(string $coll ,iterable $query): Find {
    return new Find($coll ,$query);
  }
}
