<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class BorderSide extends \Lenra\App\Base\Components\Styles\BorderSideBase {
  // Add here custom implementations

  public static function builder(): BorderSide {
    return new BorderSide();
  }
}
