<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class BorderRadius extends \Lenra\App\Base\Components\Styles\BorderRadiusBase {
  // Add here custom implementations

  public static function builder(): BorderRadius {
    return new BorderRadius();
  }
}
