<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class BoxConstraints extends \Lenra\App\Base\Components\Styles\BoxConstraintsBase {
  // Add here custom implementations

  public static function builder(): BoxConstraints {
    return new BoxConstraints();
  }
}
