<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class BoxDecoration extends \Lenra\App\Base\Components\Styles\BoxDecorationBase {
  // Add here custom implementations

  public static function builder(): BoxDecoration {
    return new BoxDecoration();
  }
}
