<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class BoxShadow extends \Lenra\App\Base\Components\Styles\BoxShadowBase {
  // Add here custom implementations

  public static function builder(): BoxShadow {
    return new BoxShadow();
  }
}
