<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class CarouselOptions extends \Lenra\App\Base\Components\Styles\CarouselOptionsBase {
  // Add here custom implementations

  public static function builder(): CarouselOptions {
    return new CarouselOptions();
  }
}
