<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class CheckboxStyle extends \Lenra\App\Base\Components\Styles\CheckboxStyleBase {
  // Add here custom implementations

  public static function builder(): CheckboxStyle {
    return new CheckboxStyle();
  }
}
