<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class Duration extends \Lenra\App\Base\Components\Styles\DurationBase {
  // Add here custom implementations

  public static function builder(): Duration {
    return new Duration();
  }
}
