<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class InputDecoration extends \Lenra\App\Base\Components\Styles\InputDecorationBase {
  // Add here custom implementations

  public static function builder(): InputDecoration {
    return new InputDecoration();
  }
}
