<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class InputBorder extends \Lenra\App\Base\Components\Styles\InputBorderBase {
  // Add here custom implementations

  public static function builder(\Lenra\App\Components\Styles\BorderSide $borderSide): InputBorder {
    return new InputBorder($borderSide);
  }
}
