<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class Locale extends \Lenra\App\Base\Components\Styles\LocaleBase {
  // Add here custom implementations

  public static function builder(): Locale {
    return new Locale();
  }
}
