<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class Offset extends \Lenra\App\Base\Components\Styles\OffsetBase {
  // Add here custom implementations

  public static function builder(): Offset {
    return new Offset();
  }
}
