<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class OutlinedBorder extends \Lenra\App\Base\Components\Styles\OutlinedBorderBase {
  // Add here custom implementations

  public static function builder(): OutlinedBorder {
    return new OutlinedBorder();
  }
}
