<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class Padding extends \Lenra\App\Base\Components\Styles\PaddingBase {
  // Add here custom implementations

  public static function builder(): Padding {
    return new Padding();
  }
}
