<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class Radius extends \Lenra\App\Base\Components\Styles\RadiusBase {
  // Add here custom implementations

  public static function builder(): Radius {
    return new Radius();
  }
}
