<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class RadioStyle extends \Lenra\App\Base\Components\Styles\RadioStyleBase {
  // Add here custom implementations

  public static function builder(): RadioStyle {
    return new RadioStyle();
  }
}
