<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class Rect extends \Lenra\App\Base\Components\Styles\RectBase {
  // Add here custom implementations

  public static function builder(): Rect {
    return new Rect();
  }
}
