<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class SliderStyle extends \Lenra\App\Base\Components\Styles\SliderStyleBase {
  // Add here custom implementations

  public static function builder(): SliderStyle {
    return new SliderStyle();
  }
}
