<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class TextStyle extends \Lenra\App\Base\Components\Styles\TextStyleBase {
  // Add here custom implementations

  public static function builder(): TextStyle {
    return new TextStyle();
  }
}
