<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class TextFieldStyle extends \Lenra\App\Base\Components\Styles\TextFieldStyleBase {
  // Add here custom implementations

  public static function builder(): TextFieldStyle {
    return new TextFieldStyle();
  }
}
