<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class TextInputType extends \Lenra\App\Base\Components\Styles\TextInputTypeBase {
  // Add here custom implementations

  public static function builder(): TextInputType {
    return new TextInputType();
  }
}
