<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class ToggleStyle extends \Lenra\App\Base\Components\Styles\ToggleStyleBase {
  // Add here custom implementations

  public static function builder(): ToggleStyle {
    return new ToggleStyle();
  }
}
