<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components\Styles;

class ToolbarOptions extends \Lenra\App\Base\Components\Styles\ToolbarOptionsBase {
  // Add here custom implementations

  public static function builder(): ToolbarOptions {
    return new ToolbarOptions();
  }
}
