<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Actionable extends \Lenra\App\Base\Components\ActionableBase {
  // Add here custom implementations

  public static function builder($child): Actionable {
    return new Actionable($child);
  }
}
