<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Button extends \Lenra\App\Base\Components\ButtonBase {
  // Add here custom implementations

  public static function builder(string $text): Button {
    return new Button($text);
  }
}
