<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Carousel extends \Lenra\App\Base\Components\CarouselBase {
  // Add here custom implementations

  public static function builder(array $children): Carousel {
    return new Carousel($children);
  }
}
