<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Checkbox extends \Lenra\App\Base\Components\CheckboxBase {
  // Add here custom implementations

  public static function builder(bool $value): Checkbox {
    return new Checkbox($value);
  }
}
