<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Container extends \Lenra\App\Base\Components\ContainerBase {
  // Add here custom implementations

  public static function builder(): Container {
    return new Container();
  }
}
