<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Flexible extends \Lenra\App\Base\Components\FlexibleBase {
  // Add here custom implementations

  public static function builder($child): Flexible {
    return new Flexible($child);
  }
}
