<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Flex extends \Lenra\App\Base\Components\FlexBase {
  // Add here custom implementations

  public static function builder(array $children): Flex {
    return new Flex($children);
  }
}
