<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Form extends \Lenra\App\Base\Components\FormBase {
  // Add here custom implementations

  public static function builder($child): Form {
    return new Form($child);
  }
}
