<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Icon extends \Lenra\App\Base\Components\IconBase {
  // Add here custom implementations

  public static function builder(string $value): Icon {
    return new Icon($value);
  }
}
