<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Listener extends \Lenra\App\Base\Components\ListenerBase {
  // Add here custom implementations

  public static function builder(string $name): Listener {
    return new Listener($name);
  }
}
