<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class MenuItem extends \Lenra\App\Base\Components\MenuItemBase {
  // Add here custom implementations

  public static function builder(string $text): MenuItem {
    return new MenuItem($text);
  }
}
