<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Menu extends \Lenra\App\Base\Components\MenuBase {
  // Add here custom implementations

  public static function builder(array $children): Menu {
    return new Menu($children);
  }
}
