<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class OverlayEntry extends \Lenra\App\Base\Components\OverlayEntryBase {
  // Add here custom implementations

  public static function builder($child): OverlayEntry {
    return new OverlayEntry($child);
  }
}
