<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Slider extends \Lenra\App\Base\Components\SliderBase {
  // Add here custom implementations

  public static function builder(): Slider {
    return new Slider();
  }
}
