<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Stack extends \Lenra\App\Base\Components\StackBase {
  // Add here custom implementations

  public static function builder(array $children): Stack {
    return new Stack($children);
  }
}
