<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Text extends \Lenra\App\Base\Components\TextBase {
  // Add here custom implementations

  public static function builder(string $value): Text {
    return new Text($value);
  }
}
