<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class TextField extends \Lenra\App\Base\Components\TextFieldBase {
  // Add here custom implementations

  public static function builder(string $value): TextField {
    return new TextField($value);
  }
}
