<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Textfield extends \Lenra\App\Base\Components\TextfieldBase {
  // Add here custom implementations

  public static function builder(string $value): Textfield {
    return new Textfield($value);
  }
}
