<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Toggle extends \Lenra\App\Base\Components\ToggleBase {
  // Add here custom implementations

  public static function builder(bool $value): Toggle {
    return new Toggle($value);
  }
}
