<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class View extends \Lenra\App\Base\Components\ViewBase {
  // Add here custom implementations

  public static function builder(string $name): View {
    return new View($name);
  }
}
