<?php
// This file is auto-generated by generate-classes.php but it can be edited

namespace Lenra\App\Components;

class Wrap extends \Lenra\App\Base\Components\WrapBase {
  // Add here custom implementations

  public static function builder(array $children): Wrap {
    return new Wrap($children);
  }
}
